# Generated by Django 6.0 on 2025-12-19 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="chaiVariy",
            new_name="chaiVarity",
        ),
    ]
