# Generated by Django 6.0 on 2025-12-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0002_rename_chaivariy_chaivarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
