# Generated by Django 6.0 on 2025-12-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0003_chaivarity_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
