# Generated by Django 6.0 on 2025-12-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0004_chaivarity_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name="chaivarity",
            name="price",
        ),
    ]
