# Generated by Django 6.0 on 2025-12-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0005_chai_remove_chaivarity_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chai",
        ),
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
