# Generated by Django 6.0 on 2025-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0007_chaicertification_chaireview_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaicertification",
            name="certification_body",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
