# Generated by Django 6.0 on 2025-12-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0008_chaicertification_certification_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="rating",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
